# syntax=docker/dockerfile:1
FROM node:20-slim

# Install PostgreSQL client tools
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --prod

COPY restore.js .

# Entrypoint for restore
ENTRYPOINT ["node", "restore.js"]
